# Lightning Training Configuration Example
#
# This configuration demonstrates how to train a weather analogue model
# using PyTorch Lightning.

# Data configuration
data:
  # Data source
  processed_data_path: data/processed/d2muvmslr_3h_none_log_20012020_weighted.h5
  
  # Data parameters
  variables: ["d2m", "u", "v", "msl", "r"]
  frequency: 3h
  time_interval: 45
  num_samples: 1000
  
# Model configuration
model:
  type: atmodist_revised  # Use the revised model with Lightning support
  num_classes: 15  # Default for 3h frequency with 24h interval
  res_in_channels: 5  # Default for 5 variables
  res_out_channels_list: [16, 32, 64]  # Default value from atmodist_revised.py
  learning_rate: 0.005  # 稍微降低學習率以獲得更穩定的訓練曲線
  momentum: 0.9
  weight_decay: 1e-5
  optimizer: sgd
  scheduler: reduce_on_plateau
  loss_type: cross_entropy
  dropout: 0.2
  
# Training configuration
training:
  epochs: 20
  batch_size: 32  # 減小批次大小以獲得更多的步數和更頻繁的記錄
  train_val_split: 0.8
  validation_interval: 1
  early_stopping: true
  patience: 10
  
# WandB configuration
wandb:
  project: weather-analogue-lightning
  entity: dylan1120  # Replace with your entity
  tags: ["lightning", "atmodist", "revised"]
  
# Specify to use Lightning
use_lightning: true
